[package]
name = "image-download"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.2.0"
reqwest = "0.11.6"
tokio = { version = "1", features = ["full"] }
error-chain = "0.12.4"