import { Button, VerticalBox } from "std-widgets.slint";

component MyText inherits Text {
    color: red;

}

component MyButton inherits Button {
    property <string> meme: "You are stupid";
    text: "Click Me"+ meme;
}

export component AppWindow inherits Window {
   width : 200px;
   height: 200px;
//    GridLayout {
//         spacing: 3px;
//         Row {
//             Rectangle { background: white; }
//             Rectangle { background: blue; }
//         }
//         Row {
//             Rectangle { background: yellow; }
//             Rectangle { background: green; }
//         }
//     } 
    MyText {
        text: "Welcome to the Grid";
        font-family: "Arial";
        font-size: 20px;
    }
    VerticalLayout {
        alignment: start;
        MyButton {
            width : 50px;
            height : 50px;
    //         clicked => {
    //             println!("Naybe you are")
    //         };
    // }

    }
}
    
}

